Repository CMPUT301F19T25/0.8XEng, pull requests merged in 2019-11, with the labels that each got.

#50 Added docs and comments to my code
  source/app/src/main/java/com/example/emote/FireStoreHandler.java
  source/app/src/main/java/com/example/emote/LoginActivity.java
  source/app/src/main/java/com/example/emote/LoginHelper.java
  source/app/src/main/java/com/example/emote/MainActivity.java
  source/app/src/main/java/com/example/emote/SignupActivity.java
  source/app/src/main/java/com/example/emote/ui/friends/FriendsFragment.java
  source/app/src/main/java/com/example/emote/ui/friends/FriendsListAdapter.java
  source/app/src/main/java/com/example/emote/ui/friends/FriendsViewModel.java
Labels: Risk - Low, documentation, sprint-2

#63 Bug fix for the Signup Page
  source/app/src/main/java/com/example/emote/SignupActivity.java
Labels: Risk - High, bug

#78 Login signup test fixes
  source/app/build.gradle
  source/app/src/androidTest/java/com/example/emote/LoginTest.java
  source/app/src/androidTest/java/com/example/emote/SignupTest.java
  source/app/src/main/java/com/example/emote/LoginActivity.java
  source/app/src/main/java/com/example/emote/SignupActivity.java
Labels: enhancement

#79 Added sign out button, number of friends following, and functionality to view a list of friends following and their current moods.
  source/app/src/main/AndroidManifest.xml
  source/app/src/main/java/com/example/emote/FollowingListActivity.java
  source/app/src/main/java/com/example/emote/FollowingListAdapter.java
  source/app/src/main/java/com/example/emote/LoginActivity.java
  source/app/src/main/java/com/example/emote/MainActivity.java
  source/app/src/main/java/com/example/emote/ui/addemote/AddEmoteViewModel.java
  source/app/src/main/java/com/example/emote/ui/profile/ProfileFragment.java
  source/app/src/main/res/layout/activity_list_following.xml
  source/app/src/main/res/layout/fragment_profile.xml
  source/app/src/main/res/layout/list_individual_following.xml
Labels: enhancement

#90 Force reason to be < 20 chars, < 3 words
  source/app/src/main/java/com/example/emote/EmotionEvent.java
  source/app/src/test/java/com/example/emote/EmotionEventTest.java
Labels: bug

#96 Added javadocs for all the classes and class methods
  source/app/src/main/java/com/example/emote/EditEventActivity.java
  source/app/src/main/java/com/example/emote/EmoteApplication.java
  source/app/src/main/java/com/example/emote/EmotionEvent.java
  source/app/src/main/java/com/example/emote/FireStoreHandler.java
  source/app/src/main/java/com/example/emote/FollowingListActivity.java
  source/app/src/main/java/com/example/emote/FollowingListAdapter.java
  source/app/src/main/java/com/example/emote/LoginActivity.java
  source/app/src/main/java/com/example/emote/LoginHelper.java
  source/app/src/main/java/com/example/emote/MainActivity.java
  source/app/src/main/java/com/example/emote/MapsActivity.java
  source/app/src/main/java/com/example/emote/SignupActivity.java
  source/app/src/main/java/com/example/emote/Situation.java
  source/app/src/main/java/com/example/emote/ui/addemote/AddEmoteFragment.java
  source/app/src/main/java/com/example/emote/ui/friends/FriendsFragment.java
  source/app/src/main/java/com/example/emote/ui/friends/FriendsListAdapter.java
  source/app/src/main/java/com/example/emote/ui/friends/FriendsViewModel.java
  source/app/src/main/java/com/example/emote/ui/friends/SearchListAdapter.java
  source/app/src/main/java/com/example/emote/ui/listemote/EmoteListAdapter.java
  source/app/src/main/java/com/example/emote/ui/listemote/ListEmoteFragment.java
  source/app/src/main/java/com/example/emote/ui/listemote/ListEmoteViewModel.java
  source/app/src/main/java/com/example/emote/ui/map/MapFragment.java
  source/app/src/main/java/com/example/emote/ui/map/MapViewModel.java
  source/app/src/main/java/com/example/emote/ui/profile/ProfileFragment.java
  source/app/src/main/java/com/example/emote/ui/profile/ProfileViewModel.java
Labels: documentation

#94 Changed friends count text to button, added background color and emoticon for each following list item.
  source/app/src/main/java/com/example/emote/FollowingListActivity.java
  source/app/src/main/java/com/example/emote/FollowingListAdapter.java
  source/app/src/main/java/com/example/emote/ui/profile/ProfileFragment.java
  source/app/src/main/res/layout/fragment_profile.xml
  source/app/src/main/res/layout/list_individual_following.xml
Labels: enhancement

#95 Styled Edit Emote Activity
  source/app/src/main/java/com/example/emote/EditEventActivity.java
  source/app/src/main/java/com/example/emote/ui/listemote/ListEmoteFragment.java
  source/app/src/main/res/layout/activity_edit_event.xml
Labels: enhancement

#98 get rid of the data class
  source/app/src/main/java/com/example/emote/EmotionEvent.java
  source/app/src/main/java/com/example/emote/ui/listemote/ListEmoteViewModel.java
Labels: enhancement
